excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Halvi.github.io
title: Shreekar Halvi
email: shreekarhalvi@gmail.com
author: Shreekar Halvi
description: Thoughts , Stories and Ideas.
paginate: 3
google_analytics: 
